[package]
name = "first-rust-crud-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ntex={version = "1.0",features = ["tokio"]}

futures = "0.3"
env_logger = "0.11"
uuid={version = "1",features = ["v4"]}

r2d2= "0.8"
r2d2_sqlite= "0.24"
rusqlite = { version = "0.31.0", features = ["bundled"] }
log = "0.4.21"
